// File: BACKEND-UAS/main.go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	fiberSwagger "github.com/swaggo/fiber-swagger" // ✅ Import yang benar untuk Swagger di Fiber

	"BACKEND-UAS/config"
	"BACKEND-UAS/middleware"
	"BACKEND-UAS/pgmongo/jwt"
	"BACKEND-UAS/pgmongo/repository"
	"BACKEND-UAS/pgmongo/service"
	"BACKEND-UAS/route"

	// Swagger docs (generated by swag init)
	_ "BACKEND-UAS/docs"
)

// @title BACKEND-UAS API
// @version 1.0
// @description API untuk sistem manajemen user, achievement, student, lecturer, dan report
// @host localhost:3000
// @BasePath /api/v1/  //
// @schemes http

func main() {
	cfg := config.NewConfig()

	// ============================
	// INIT SERVICES
	// ============================
	userRepo := repository.NewUserRepository(cfg.Connection.PostgresDB)
	jwtSvc := jwt.NewJWTService(cfg.JWTSecret)
	authSvc := service.NewAuthService(userRepo, jwtSvc)
	userSvc := service.NewUserService(userRepo, jwtSvc)
	authMiddleware := middleware.NewAuthMiddleware(jwtSvc, userRepo)

	// Achievement repos
	achievementPgRepo := repository.NewAchievementRepository(cfg.Connection.PostgresDB)
	achievementMongoRepo := repository.NewAchievementRepositoryMongo(cfg.Connection.MongoClient)
	achievementSvc := service.NewAchievementService(achievementPgRepo, achievementMongoRepo)

	// Student repos and services
	studentRepo := repository.NewStudentRepository(cfg.Connection.PostgresDB)
	studentSvc := service.NewStudentService(studentRepo, achievementPgRepo)

	// Lecturer repos and services
	lecturerRepo := repository.NewLecturerRepository(cfg.Connection.PostgresDB)
	lecturerSvc := service.NewLecturerService(lecturerRepo, studentRepo)

	// Report repos and services
	reportRepo := repository.NewReportRepository(cfg.Connection.PostgresDB, achievementMongoRepo)
	reportSvc := service.NewReportService(reportRepo, studentRepo, lecturerRepo)

	// ============================
	// INIT FIBER APP
	// ============================
	app := fiber.New(fiber.Config{
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			return c.Status(500).JSON(fiber.Map{"status": "error", "message": err.Error()})
		},
	})

	// CORS middleware (buat Postman/browser)
	app.Use(cors.New())

	// Routes
	route.AuthRoute(app, authSvc, authMiddleware)
	route.UserRoute(app, userSvc, authMiddleware)
	route.SetupAchievementRoutes(app, achievementSvc, authMiddleware)
	route.SetupStudentRoutes(app, studentSvc, authMiddleware)   // Pass authMiddleware for student routes
	route.SetupLecturerRoutes(app, lecturerSvc, authMiddleware) // Pass authMiddleware for lecturer routes
	route.SetupReportRoutes(app, reportSvc, authMiddleware)

	// Health check
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "OK"})
	})

	// ============================
	// 📚 Setup Swagger UI (Pasti jalan)
	// ===========================
	// Jalankan perintah ini dulu:
	// go install github.com/swaggo/swag/cmd/swag@latest
	// swag init -g main.go
	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	// ============================
	// 🧠 Graceful shutdown (opsional, tapi bagus buat production)
	// ============================
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-quit
		log.Println("🛑 Shutting down server...")

		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		if err := app.ShutdownWithContext(ctx); err != nil {
			log.Printf("Error shutting down app: %v", err)
		}

		// Tutup koneksi DB kalau ada (sesuaikan dengan config kamu)
		if cfg.Connection.PostgresDB != nil {
			if err := cfg.Connection.PostgresDB.Close(); err != nil {
				log.Printf("Error closing Postgres DB: %v", err)
			} else {
				log.Println("🔌 Postgres DB closed")
			}
		}

		if cfg.Connection.MongoClient != nil {
			if err := cfg.Connection.MongoClient.Disconnect(context.Background()); err != nil {
				log.Printf("Error disconnecting MongoDB: %v", err)
			} else {
				log.Println("🔌 MongoDB disconnected")
			}
		}

		os.Exit(0)
	}()

	// ============================
	// RUN SERVER
	// ============================
	port := cfg.Port // Asumsi cfg.Port udah string
	if port == "" {
		port = "3000"
	}

	url := fmt.Sprintf("http://localhost:%s", port)

	log.Printf("🚀 Server running on %s\n", url)
	log.Printf("📚 Swagger docs: %s/swagger/index.html\n", url)
	log.Println("💡 Tips:")
	log.Println("  1️⃣ go install github.com/swaggo/swag/cmd/swag@latest")
	log.Println("  2️⃣ swag init -g main.go")
	log.Println("  3️⃣ Restart server")

	if err := app.Listen(":" + port); err != nil {
		log.Fatalf("❌ Failed to start server: %v", err)
	}
}
